//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Match
{

    private MatchHomeTeam homeTeamField;

    private MatchAwayTeam awayTeamField;

    private MatchResult resultField;

    private string venueLocationField;

    private System.DateTime eventTimeField;

    private decimal totalPriceField;

    private decimal pricePerPersonField;

    private bool wasCanceledField;

    private string reportField;

    private string logisticsInformationField;

    private sbyte playersPerTeamField;

    private MatchType typeField;

    private MatchPitchType pitchTypeField;

    private MatchPitchLocation pitchLocationField;

    private MatchGeographicalLocation geographicalLocationField;

    /// <remarks/>
    public MatchHomeTeam HomeTeam
    {
        get
        {
            return this.homeTeamField;
        }
        set
        {
            this.homeTeamField = value;
        }
    }

    /// <remarks/>
    public MatchAwayTeam AwayTeam
    {
        get
        {
            return this.awayTeamField;
        }
        set
        {
            this.awayTeamField = value;
        }
    }

    /// <remarks/>
    public MatchResult Result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }

    /// <remarks/>
    public string VenueLocation
    {
        get
        {
            return this.venueLocationField;
        }
        set
        {
            this.venueLocationField = value;
        }
    }

    /// <remarks/>
    public System.DateTime EventTime
    {
        get
        {
            return this.eventTimeField;
        }
        set
        {
            this.eventTimeField = value;
        }
    }

    /// <remarks/>
    public decimal TotalPrice
    {
        get
        {
            return this.totalPriceField;
        }
        set
        {
            this.totalPriceField = value;
        }
    }

    /// <remarks/>
    public decimal PricePerPerson
    {
        get
        {
            return this.pricePerPersonField;
        }
        set
        {
            this.pricePerPersonField = value;
        }
    }

    /// <remarks/>
    public bool WasCanceled
    {
        get
        {
            return this.wasCanceledField;
        }
        set
        {
            this.wasCanceledField = value;
        }
    }

    /// <remarks/>
    public string Report
    {
        get
        {
            return this.reportField;
        }
        set
        {
            this.reportField = value;
        }
    }

    /// <remarks/>
    public string LogisticsInformation
    {
        get
        {
            return this.logisticsInformationField;
        }
        set
        {
            this.logisticsInformationField = value;
        }
    }

    /// <remarks/>
    public sbyte PlayersPerTeam
    {
        get
        {
            return this.playersPerTeamField;
        }
        set
        {
            this.playersPerTeamField = value;
        }
    }

    /// <remarks/>
    public MatchType Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public MatchPitchType PitchType
    {
        get
        {
            return this.pitchTypeField;
        }
        set
        {
            this.pitchTypeField = value;
        }
    }

    /// <remarks/>
    public MatchPitchLocation PitchLocation
    {
        get
        {
            return this.pitchLocationField;
        }
        set
        {
            this.pitchLocationField = value;
        }
    }

    /// <remarks/>
    public MatchGeographicalLocation GeographicalLocation
    {
        get
        {
            return this.geographicalLocationField;
        }
        set
        {
            this.geographicalLocationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class MatchHomeTeam
{

    private MatchHomeTeamTeam teamField;

    /// <remarks/>
    public MatchHomeTeamTeam Team
    {
        get
        {
            return this.teamField;
        }
        set
        {
            this.teamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class MatchHomeTeamTeam
{

    private string nameField;

    private MatchHomeTeamTeamPlayer[] playersField;

    private string idField;

    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Player", IsNullable = false)]
    public MatchHomeTeamTeamPlayer[] Players
    {
        get
        {
            return this.playersField;
        }
        set
        {
            this.playersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class MatchHomeTeamTeamPlayer
{

    private string idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class MatchAwayTeam
{

    private MatchAwayTeamTeam teamField;

    /// <remarks/>
    public MatchAwayTeamTeam Team
    {
        get
        {
            return this.teamField;
        }
        set
        {
            this.teamField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class MatchAwayTeamTeam
{

    private string nameField;

    private MatchAwayTeamTeamPlayer[] playersField;

    private string idField;

    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Player", IsNullable = false)]
    public MatchAwayTeamTeamPlayer[] Players
    {
        get
        {
            return this.playersField;
        }
        set
        {
            this.playersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class MatchAwayTeamTeamPlayer
{

    private string idField;

    private string valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class MatchResult
{

    private int homeResultField;

    private int awayResultField;

    /// <remarks/>
    public int HomeResult
    {
        get
        {
            return this.homeResultField;
        }
        set
        {
            this.homeResultField = value;
        }
    }

    /// <remarks/>
    public int AwayResult
    {
        get
        {
            return this.awayResultField;
        }
        set
        {
            this.awayResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum MatchType
{

    /// <remarks/>
    FutSal,

    /// <remarks/>
    Football,

    /// <remarks/>
    Basketball,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum MatchPitchType
{

    /// <remarks/>
    Vynil,

    /// <remarks/>
    SintheticGrass,

    /// <remarks/>
    GrassMat,

    /// <remarks/>
    Wood,

    /// <remarks/>
    Grass,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum MatchPitchLocation
{

    /// <remarks/>
    Indoor,

    /// <remarks/>
    Outdoor,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum MatchGeographicalLocation
{

    /// <remarks/>
    Telheiras,

    /// <remarks/>
    Damaia,
}
